// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfigugwfmoqlpzhbddxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmaWd1Z3dmbW9xbHB6aGJkZHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDUwMDYsImV4cCI6MjA2NTQ4MTAwNn0.0XiwuT3t0he9e932eliZ5YWV3c4pHjlcKOPk-ZoNOf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);